In [14]:
import pandas as pd

metadata = pd.read_csv("../data/raw/metadata.csv")
metadata.head()

,building_id,site_id,building_id_kaggle,site_id_kaggle,primaryspaceusage,sub_primaryspaceusage,sqm,sqft,lat,lng,...,yearbuilt,date_opened,numberoffloors,occupants,energystarscore,eui,site_eui,source_eui,leed_level,rating
0,Panther_lodging_Dean,Panther,NaN,0.0,Lodging/residential,Residence Hall,508.8,5477.0,28.517689,-81.379039,...,1989.0,NaN,NaN,NaN,NaN,271,NaN,NaN,NaN,NaN
1,Panther_lodging_Shelia,Panther,NaN,0.0,Lodging/residential,Residence Hall,929.0,10000.0,28.517689,-81.379039,...,1992.0,NaN,NaN,NaN,NaN,62,NaN,NaN,NaN,NaN
2,Panther_lodging_Ricky,Panther,NaN,0.0,Lodging/residential,Residence Hall,483.1,5200.0,28.517689,-81.379039,...,2016.0,NaN,NaN,NaN,NaN,534,NaN,NaN,NaN,NaN
3,Panther_education_Rosalie,Panther,0.0,0.0,Education,Research,690.5,7432.0,28.517689,-81.379039,...,2008.0,NaN,NaN,NaN,NaN,276,NaN,NaN,NaN,NaN
4,Panther_education_Misty,Panther,1.0,0.0,Education,Research,252.7,2720.0,28.517689,-81.379039,...,2004.0,NaN,NaN,NaN,NaN,375,NaN,NaN,NaN,NaN

In [15]:
metadata.shape

(1636, 32)

In [16]:
metadata['site_id'].unique()

<StringArray>
[ 'Panther',    'Robin',      'Fox',      'Rat',     'Bear',     'Lamb',
  'Peacock',    'Moose',    'Gator',     'Bull',   'Bobcat',     'Crow',
    'Shrew',     'Swan',     'Wolf',      'Hog',    'Eagle', 'Cockatoo',
    'Mouse']
Length: 19, dtype: str

In [17]:
metadata['site_id'].value_counts()

site_id
Rat         305
Hog         163
Lamb        147
Fox         137
Panther     136
Bull        124
Cockatoo    124
Eagle       106
Bear         92
Gator        74
Robin        52
Peacock      47
Bobcat       36
Wolf         36
Swan         21
Moose        15
Shrew         9
Mouse         7
Crow          5
Name: count, dtype: int64

In [18]:
panther_buildings = metadata[metadata['site_id'] == 'Panther']
panther_buildings['primaryspaceusage'].value_counts()

primaryspaceusage
Lodging/residential              44
Education                        35
Office                           28
Parking                           9
Other                             8
Retail                            7
Entertainment/public assembly     5
Name: count, dtype: int64

In [19]:
electricity = pd.read_csv("../data/raw/electricity_cleaned.csv")
electricity.shape

(17544, 1579)

In [20]:
electricity.columns[:10]

Index(['timestamp', 'Panther_parking_Lorriane', 'Panther_lodging_Cora',
       'Panther_office_Hannah', 'Panther_lodging_Hattie',
       'Panther_education_Teofila', 'Panther_education_Jerome',
       'Panther_retail_Felix', 'Panther_parking_Asia',
       'Panther_education_Misty'],
      dtype='str')

In [21]:
panther_building_ids = panther_buildings['building_id'].tolist()
len(panther_building_ids)

136

In [22]:
columns_to_keep = ['timestamp'] + panther_building_ids
electricity_panther = electricity[columns_to_keep]
electricity_panther.shape

KeyError: "['Panther_lodging_Dean', 'Panther_lodging_Shelia', 'Panther_lodging_Ricky', 'Panther_office_Daina', 'Panther_office_Woodrow', 'Panther_education_Guillermina', 'Panther_lodging_Amos', 'Panther_lodging_Bonnie', 'Panther_education_Richard', 'Panther_lodging_Arlene', 'Panther_education_Lacey', 'Panther_lodging_Aaron', 'Panther_office_Bryce', 'Panther_lodging_Heather', 'Panther_lodging_Otis', 'Panther_lodging_Jacquelyn', 'Panther_lodging_Juliet', 'Panther_lodging_Carroll', 'Panther_lodging_Paulette', 'Panther_lodging_Alyssa', 'Panther_other_Iva', 'Panther_other_Luis', 'Panther_office_Gino', 'Panther_parking_Clarence', 'Panther_lodging_Drew', 'Panther_retail_Jeanette', 'Panther_other_Ismael', 'Panther_education_Jarrett', 'Panther_lodging_Georgie', 'Panther_education_Joyce', 'Panther_lodging_Marlyn'] not in index"

In [23]:
available_columns = electricity.columns.tolist()
panther_ids_available = [b for b in panther_building_ids if b in available_columns]
len(panther_ids_available)

105

In [24]:
columns_to_keep = ['timestamp'] + panther_ids_available
electricity_panther = electricity[columns_to_keep]
electricity_panther.shape

(17544, 106)

In [25]:
electricity_panther.head()

,timestamp,Panther_education_Rosalie,Panther_education_Misty,Panther_education_Mattie,Panther_education_Diann,Panther_education_Gina,Panther_education_Tina,Panther_lodging_Russell,Panther_education_Vincent,Panther_education_Shelton,...,Panther_lodging_Kara,Panther_lodging_Kirk,Panther_lodging_Cora,Panther_lodging_Marisol,Panther_office_Danica,Panther_lodging_Dianna,Panther_office_Antonette,Panther_office_Christin,Panther_education_Cleopatra,Panther_office_Ruthie
0,2016-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016-01-01 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2016-01-01 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2016-01-01 03:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,9.7519,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2016-01-01 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
electricity_long = electricity_panther.melt(
    id_vars='timestamp',
    var_name='building_id',
    value_name='meter_reading'
)
electricity_long.shape

(1842120, 3)

In [27]:
electricity_long.head(10)
electricity_long['building_id'].nunique()

105

In [28]:
electricity_long['meter_reading'].isna().mean()

np.float64(0.19812390072307992)

In [29]:
missing_per_building = electricity_long.groupby('building_id')['meter_reading'].apply(lambda x: x.isna().mean())
missing_per_building.sort_values(ascending=False).head(15)

building_id
Panther_office_Otto            0.495611
Panther_education_Quintin      0.302953
Panther_retail_Gilbert         0.248974
Panther_parking_Jody           0.241336
Panther_education_Jonathan     0.229366
Panther_office_Christin        0.225946
Panther_office_Brent           0.220645
Panther_education_Genevieve    0.214546
Panther_assembly_David         0.211924
Panther_other_Lucina           0.207421
Panther_education_Karri        0.207364
Panther_office_Graham          0.201265
Panther_parking_Stanley        0.193855
Panther_assembly_Pamella       0.193570
Panther_education_Rosalie      0.193399
Name: meter_reading, dtype: float64

In [30]:
weather = pd.read_csv("../data/raw/weather.csv")
weather.shape
weather.head()

,timestamp,site_id,airTemperature,cloudCoverage,dewTemperature,precipDepth1HR,precipDepth6HR,seaLvlPressure,windDirection,windSpeed
0,2016-01-01 00:00:00,Panther,19.4,NaN,19.4,0.0,NaN,NaN,0.0,0.0
1,2016-01-01 01:00:00,Panther,21.1,6.0,21.1,-1.0,NaN,1019.4,0.0,0.0
2,2016-01-01 02:00:00,Panther,21.1,NaN,21.1,0.0,NaN,1018.8,210.0,1.5
3,2016-01-01 03:00:00,Panther,20.6,NaN,20.0,0.0,NaN,1018.1,0.0,0.0
4,2016-01-01 04:00:00,Panther,21.1,NaN,20.6,0.0,NaN,1019.0,290.0,1.5

In [31]:
weather_panther = weather[weather['site_id'] == 'Panther']
weather_panther.shape

(17544, 10)

In [32]:
merged = electricity_long.merge(weather_panther, on='timestamp', how='left')
merged.shape
merged.head()

,timestamp,building_id,meter_reading,site_id,airTemperature,cloudCoverage,dewTemperature,precipDepth1HR,precipDepth6HR,seaLvlPressure,windDirection,windSpeed
0,2016-01-01 00:00:00,Panther_education_Rosalie,NaN,Panther,19.4,NaN,19.4,0.0,NaN,NaN,0.0,0.0
1,2016-01-01 01:00:00,Panther_education_Rosalie,NaN,Panther,21.1,6.0,21.1,-1.0,NaN,1019.4,0.0,0.0
2,2016-01-01 02:00:00,Panther_education_Rosalie,NaN,Panther,21.1,NaN,21.1,0.0,NaN,1018.8,210.0,1.5
3,2016-01-01 03:00:00,Panther_education_Rosalie,NaN,Panther,20.6,NaN,20.0,0.0,NaN,1018.1,0.0,0.0
4,2016-01-01 04:00:00,Panther_education_Rosalie,NaN,Panther,21.1,NaN,20.6,0.0,NaN,1019.0,290.0,1.5

In [33]:
merged.shape
merged.columns.tolist()

['timestamp',
 'building_id',
 'meter_reading',
 'site_id',
 'airTemperature',
 'cloudCoverage',
 'dewTemperature',
 'precipDepth1HR',
 'precipDepth6HR',
 'seaLvlPressure',
 'windDirection',
 'windSpeed']

In [34]:
final = merged.merge(panther_buildings, on='building_id', how='left')
final.shape
final.columns.tolist()

['timestamp',
 'building_id',
 'meter_reading',
 'site_id_x',
 'airTemperature',
 'cloudCoverage',
 'dewTemperature',
 'precipDepth1HR',
 'precipDepth6HR',
 'seaLvlPressure',
 'windDirection',
 'windSpeed',
 'site_id_y',
 'building_id_kaggle',
 'site_id_kaggle',
 'primaryspaceusage',
 'sub_primaryspaceusage',
 'sqm',
 'sqft',
 'lat',
 'lng',
 'timezone',
 'electricity',
 'hotwater',
 'chilledwater',
 'steam',
 'water',
 'irrigation',
 'solar',
 'gas',
 'industry',
 'subindustry',
 'heatingtype',
 'yearbuilt',
 'date_opened',
 'numberoffloors',
 'occupants',
 'energystarscore',
 'eui',
 'site_eui',
 'source_eui',
 'leed_level',
 'rating']

In [35]:
final = final.drop(columns=['site_id_y'])
final = final.rename(columns={'site_id_x': 'site_id'})
final.shape

(1842120, 42)

In [38]:
final.to_csv("../data/processed/panther_merged.csv", index=False)

OSError: Cannot save file into a non-existent directory: '..\data\processed'

In [39]:
import os
os.getcwd()

'C:\\Users\\HP\\Desktop\\energy forecasting\\notebooks'

In [42]:
os.makedirs("../data/processed", exist_ok=True)

In [44]:
final.to_csv("../data/processed/panther_merged.csv", index=False)